# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbev-hello-world',
                'doc_host': 'https://mrtushartiwari.github.io',
                'git_url': 'https://github.com/mrtushartiwari/nbev-hello-world',
                'lib_path': 'nbev_hello_world'},
  'syms': {'nbev_hello_world.core': {'nbev_hello_world.core.foo': ('core.html#foo', 'nbev_hello_world/core.py')}}}
